spring.application.name=ecom-application
server.port=8080
spring.mongodb.uri=mongodb+srv://yadavsk0709_db_user:YErbMYYJS8xBsvBl@ecomm.vqwafnb.mongodb.net/eComm
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.mongodb.enabled=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Admin credentials
app.admin.email=admin@gmail.com
app.admin.password=Admin@123

app.frontend.url=http://localhost:5173
app.payment.mode=real
app.razorpay.key_id=rzp_test_TWonc74sHqBdZj
app.razorpay.key_secret=DK2gsQW6FcdpgUDffizW9Hj3
